//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduling_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int appointmentId { get; set; }
        public int customerId { get; set; }
        public int userId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public string contact { get; set; }
        public string type { get; set; }
        public string url { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime end { get; set; }
        public System.DateTime createDate { get; set; }
        public string createdBy { get; set; }
        public System.DateTime lastUpdate { get; set; }
        public string lastUpdateBy { get; set; }

        public appointment(int appointmentId, int customerId, int userId, string title, string description,
                                string location, string contact, string type, string url, DateTime start, DateTime end,
                                DateTime createDate, string createdBy, DateTime lastUpdate, string lastUpdateBy, customer customer, user user)
        {
            this.appointmentId = appointmentId;
            this.customerId = customerId;
            this.userId = userId;
            this.title = title;
            this.description = description;
            this.location = location;
            this.contact = contact;
            this.type = type;
            this.url = url;
            this.start = start;
            this.end = end;
            this.createDate = createDate;
            this.createdBy = createdBy;
            this.lastUpdate = lastUpdate;
            this.lastUpdateBy = lastUpdateBy;
            this.user = user;
            this.customer = customer;
        }

        public appointment()
        {

        }
    
        public virtual customer customer { get; set; }
        public virtual user user { get; set; }
    }
}
